osx_image: xcode15
language: swift
xcode_project: Framework/Framework.xcodeproj
script:
  - xcodebuild clean build test -enableCodeCoverage YES -project Framework/Framework.xcodeproj -scheme Framework -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 14' ONLY_ACTIVE_ARCH=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
