name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build app
      run: xcodebuild clean build test -enableCodeCoverage YES -project Framework/CountryPicker.xcodeproj -scheme Framework -destination 'platform=iOS Simulator,name=iPhone 15' ONLY_ACTIVE_ARCH=YES

    - name: Run tests
      run: xcodebuild -project 'Framework/CountryPicker.xcodeproj' -scheme 'Framework' -destination 'platform=iOS Simulator,name=iPhone 15' test | xcpretty
