name: Update README

on:
  workflow_run:
    workflows: ["Swift"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          status=${{ job.status }}
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            status="passed"
          fi
          if [[ "${{ github.event.workflow_run.conclusion }}" == "failure" ]]; then
            status="failed"
          fi
          sed -i "s/BUILD_STATUS_PLACEHOLDER/${status}/g" README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README with build status"
          git push
